server:
  port: 8010

spring:
  application:
    name: mall-gateway
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      host: localhost
      port: 8500
