server:
  port: 8113

spring:
  application:
    name: mall-user
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
  cloud:
    consul:
      host: localhost
      port: 8500
